#!/usr/bin/env python3
"""Build wwwroot/account-modal.{js,css} for mcp.dmca.com.

Inputs (all in this folder):
  www-plan-modal.html   the plan / log in / register modal markup as served on https://www.dmca.com/add/
                        (Add/Assets/pro-comparison-modal.ascx), copied verbatim
  www-modal-css.json    every www.dmca.com CSS rule that styles that modal, captured by extract-css.js
                        (node extract-css.js) and already scoped under #dmcaAcct
  account-modal.src.js  the modal logic (port of PP2020/js/status-upgrade.js without redirects)

Usage: python3 build.py [version]
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', '..', 'azure', 'DmcaCasesMcp.Functions', 'wwwroot')
VERSION = sys.argv[1] if len(sys.argv) > 1 else '1'


def must_sub(pattern, repl, text, flags=re.S):
    new, n = re.subn(pattern, repl, text, flags=flags)
    if n == 0:
        raise SystemExit('build.py: pattern not found: ' + pattern)
    return new


ACCOUNT_PANEL = '''
                <div class="plan-acct" hidden data-reveal="0">
                    <p class="plan-auth__summary plan-acct__who">Logged in as <strong class="plan-acct__email"></strong> &middot; <span class="plan-acct__plan"></span> plan</p>
                    <div class="plan-auth__label">Your DMCA API token</div>
                    <div class="plan-acct__box"><span class="plan-acct__token mono"></span><button type="button" class="plan-acct__mini plan-acct__reveal" aria-pressed="false">Reveal</button><button type="button" class="plan-acct__mini plan-acct__copy-token">Copy</button></div>
                    <div class="plan-auth__label">MCP client config</div>
                    <pre class="plan-acct__config mono" aria-label="MCP client configuration"></pre>
                    <div class="plan-acct__tools"><button type="button" class="plan-acct__mini plan-acct__copy-config">Copy config</button></div>
                    <p class="plan-auth__fine">Send it as <strong>Authorization: Bearer &lt;token&gt;</strong> to https://mcp.dmca.com/runtime/webhooks/mcp. Kept only in this browser tab &mdash; treat it like a password.</p>
                    <button type="button" class="btn plan-auth__submit plan-acct__upgrade">Upgrade plan</button>
                    <p class="plan-auth__fine"><a href="#" class="plan-acct__logout">Log out</a></p>
                </div>
'''


def build_html():
    h = open(os.path.join(HERE, 'www-plan-modal.html'), encoding='utf-8').read()
    # Free plan buttons: in-modal register instead of www.dmca.com/toolkit/signup2.aspx.
    h = must_sub(r'href="https://www\.dmca\.com/toolkit/signup2\.aspx\?r=newpp-free"', 'href="#"', h)
    # PayPal and Crypto leave the page (paypal.com / pay.boomfi.xyz): not offered here.
    h = must_sub(r'(<button type="button" class="plan-pay-toggle__opt" data-pay="paypal")', r'\1 hidden', h)
    h = must_sub(r'(<button type="button" class="plan-pay-toggle__opt" data-pay="crypto")', r'\1 hidden', h)
    # Credit Card is then the only method, so the one-option method switch is hidden too.
    h = must_sub(r'(<div class="plan-pay-toggle plan-pay-toggle--shared")', r'\1 hidden', h)
    # Registration goes to api.dmca.com/register (no reCAPTCHA step).
    h = must_sub(r'<p class="plan-auth__fine">We&rsquo;ll email your login details\..*?</p>', '<p class="plan-auth__fine">We&rsquo;ll email your login details.</p>', h)
    h = must_sub(r'\s*<div class="plan-auth__recaptcha"[^>]*></div>', '', h)
    # Google sign-in needs www.dmca.com/users/googlelogin.aspx on the same origin: not offered here.
    h = must_sub(r'\s*<button type="button" class="btn plan-auth__google">.*?</button>', '', h)
    h = must_sub(r'href="/users/login\.aspx\?r=resetpw_status"', 'href="https://www.dmca.com/users/login.aspx?r=resetpw_mcp"', h)
    h = must_sub(r'(\s*<div class="plan-auth__progress")', ACCOUNT_PANEL.rstrip('\n') + r'\1', h)
    h = re.sub(r'<!--.*?-->', '', h, flags=re.S)
    h = re.sub(r'[ \t]+\n', '\n', h)
    h = re.sub(r'\n{2,}', '\n', h)
    return '<div class="redirectModalVeil"></div>\n' + h.strip() + '\n'


CSS_HEAD = '''/*!
 * mcp.dmca.com account modal styles. Generated by tools/account-modal/build.py - do not edit by hand.
 * The rules below the marker are www.dmca.com's own CSS for the /add/ plan modal (bundle.css,
 * plan-comparison-modal.css, add-plan-compare.css, /add/ inline styles), scoped under #dmcaAcct.
 */
html.dmca-acct-open, html.dmca-acct-open body { overflow: hidden; }
#dmcaAcct { font-family: "Google+Sans", Arial, sans-serif; font-size: 14px; line-height: 17.5px; font-weight: 400; color: rgb(31, 31, 31); letter-spacing: normal; text-align: left; -webkit-font-smoothing: antialiased; }
/* Neutralise this page's own .btn / code / link styles inside the modal (lowest specificity, so www rules win). */
:where(#dmcaAcct) .btn { display: inline-block; align-items: normal; justify-content: normal; padding: 0; border-radius: 0; font-weight: normal; border: 0; transition: none; background: none; color: inherit; }
:where(#dmcaAcct) .btn:hover { transform: none; }
:where(#dmcaAcct) code, :where(#dmcaAcct) .mono { font-family: inherit; font-size: inherit; color: inherit; }
:where(#dmcaAcct) a:hover { text-decoration: none; }
/* ---- www.dmca.com rules ---- */
'''

CSS_TAIL = '''
/* ---- mcp.dmca.com additions ---- */
#dmcaAcct .redirectModalVeil { z-index: 9998; }
#dmcaAcct .plan-acct__who { margin-bottom: 14px; }
#dmcaAcct .plan-acct .plan-auth__label { display: block; margin: 14px 0 6px; font-size: 13px; font-weight: 700; color: #1f1f1f; }
#dmcaAcct .plan-acct__box { display: flex; align-items: center; gap: 8px; padding: 9px 10px 9px 12px; border: 1px solid #bdbdbd; border-radius: 8px; background: #fafafa; }
#dmcaAcct .plan-acct .mono { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12.5px; color: #1f1f1f; }
#dmcaAcct .plan-acct__token { flex: 1 1 auto; min-width: 0; word-break: break-all; line-height: 1.4; }
#dmcaAcct .plan-acct__mini { flex: 0 0 auto; appearance: none; border: 1px solid #d0d5dd; background: #fff; color: #1f1f1f; border-radius: 6px; padding: 5px 10px; font-size: 12px; font-weight: 700; line-height: 1.2; cursor: pointer; white-space: nowrap; }
#dmcaAcct .plan-acct__mini:hover { border-color: #6BC530; background: #f3faee; }
#dmcaAcct .plan-acct__mini:focus-visible { outline: 2px solid #6BC530; outline-offset: 1px; }
#dmcaAcct .plan-acct .plan-acct__config { margin: 0; padding: 10px 12px; border-radius: 8px; background: #1f1f1f; color: #d4f5bc; font-size: 12px; line-height: 1.45; white-space: pre-wrap; overflow-wrap: anywhere; }
#dmcaAcct .plan-acct__tools { display: flex; justify-content: flex-end; margin-top: 6px; }
#dmcaAcct .plan-acct .plan-acct__upgrade { margin-top: 16px; }
#dmcaAcct .plan-acct__logout { color: #4c9a1f; font-weight: 700; }
#dmcaAcct .plan-acct__logout:hover { text-decoration: underline; }
'''


def build_css():
    data = json.load(open(os.path.join(HERE, 'www-modal-css.json'), encoding='utf-8'))
    parts = []
    for r in data['out']:
        text = r['text']
        for cond in reversed(r['media']):
            text = (cond if cond.startswith('@supports') else '@media ' + cond) + ' {\n' + text + '\n}'
        parts.append(text)
    parts.extend(data['anims'])
    return CSS_HEAD + '\n'.join(parts) + '\n' + CSS_TAIL


def main():
    html = build_html()
    src = open(os.path.join(HERE, 'account-modal.src.js'), encoding='utf-8').read()
    if '__MODAL_HTML__' not in src:
        raise SystemExit('missing __MODAL_HTML__')
    js = src.replace('__MODAL_HTML__', json.dumps(html)).replace('__VERSION__', VERSION)
    js = js.replace(' * Built by tools/account-modal/build.py - edit the source there, not wwwroot/account-modal.js.',
                    ' * Generated by tools/account-modal/build.py from account-modal.src.js - do not edit by hand.')
    with open(os.path.join(OUT, 'account-modal.js'), 'w', encoding='utf-8', newline='\n') as f:
        f.write(js)
    with open(os.path.join(OUT, 'account-modal.css'), 'w', encoding='utf-8', newline='\n') as f:
        f.write(build_css())
    print('built version', VERSION, len(js), 'bytes js')


if __name__ == '__main__':
    main()
